### ISSUE TITLE
Support JSON array in the form of lists/enumerations of `OneOf` discriminated unions

### ISSUE THREAD

**Issue by r-arjocu** [dpraimeyuu/OneOf.Serialization#1]
If I have a C# class, like this one:
```
public partial class SomeClass: IEquatable<SomeClass>
{
	[DataMember (Name = "first_channel", EmitDefaultValue = false)]
	[JsonConverter (typeof (OneOfJsonConverter<OneOf<int, SomeOtherClass>>))]
	public OneOf<int, SomeOtherClass> FirstChannel { get; set; }

	...
}
```
serializing and deserializing using `OneOf.Serialization` goes well.

But if a have a list of discriminated unions, as following:
```
public partial class SomeClass: IEquatable<SomeClass>
{
	[DataMember (Name = "channels", EmitDefaultValue = false)]
	[JsonConverter (typeof (OneOfJsonConverter<List<OneOf<int, SomeOtherClass>>>))]
	public List<OneOf<int, SomeOtherClass>> Channels { get; set; }

	...
}
```
serializing and deserializing throws an exception. The same result is obtained when using a general enumeration (`IEnumerable`).

Looking through the `OneOf.Serialization` code, I see that JSON arrays of `oneOf`s are not treated (just JSON objects).

**Comment by dpraimeyuu** [comment]
Hi @ra-mt ! Thanks for reaching out.

I didn't have such a need to cover but looks like a decent improvement!

PRs are opened (should be, at least), so if you can cover this scenario (as you have such example at your disposal), would be great!

**Comment by r-arjocu** [comment]
Hi @dpraimeyuu ,

I have some code ready on my local OOS-1 branch, but cannot push it. I'm not sure if I'm doing something wrong with SourceTree and HTTPS authentication, or there's a limitation on your part (still).

This coming pull request actually fixes only a scenario like this:
```
[JsonConverter(typeof(OneOfJsonConverter<SomeClass>))]
public partial class SomeClass : OneOfBas<... , ...>
{
	...
}

public partial class AnotherClass
{
	[JsonConverter(typeof(OneOfJsonConverter<List<SomeClass>>))]
	public List<SomeClass> SomeClassList { get; set; }

	...
}
```
I will cover the initial scenarios in a different issue (if there's any need to create one), and I have another pull request almost ready. Fields like `OneOf<int, float>` are actually not deserialized properly, and it was a pain to get them to work because of `OneOf`s restrictions.

Thanks!

**Comment by r-arjocu** [comment]
Never mind my push problem, it's the first time I'm working in this "fork and then merge back in original repo" style. Here is the pull req: https://github.com/dpraimeyuu/OneOf.Serialization/pull/3
